"ddg.type","ddg.num","ddg.name","ddg.value","ddg.scope","ddg.from.env","ddg.time","ddg.loc","ddg.current"
"Exception",1,"error.msg","\""Error in file(file, \""rt\""): cannot open the connection \""","ddg.library",FALSE,"","",TRUE
